### ISSUE TITLE
Android Compile Issues

### ISSUE THREAD

**Issue by mirmajeed** [RobGibbens/XamarinFormsGestureRecognizers#2]
When I compile the solution, In the FancyAndroidLabelRenderer on OnElementChanged I get the error  Error CS0070: The event `Android.Views.View.Touch' can only appear on the left hand side of += or -= when used outside of the type `Android.Views.View' .

**Comment by reinhardsual** [comment]
Have the same issue here.... No fix yet?

**Comment by thready** [comment]
Same error for me.

**Comment by thready** [comment]
Sorry to bug Rob, could you help with this?

**Comment by RobGibbens** [comment]
Sorry..I never saw these issues.  That null check never should have been there. I've removed them and [updated the code](https://github.com/RobGibbens/XamarinFormsGestureRecognizers/blob/master/Android/FancyAndroidLabelRenderer.cs#L28).
